Repository Mozilla-SKNCOE/blog, pull requests merged in 2020-10, with the labels that each got.

#2 Create 2020-10-26-tech-hidden-blog.md
  posts/2020-10-26-tech-hidden-blog.md
Labels: hacktoberfest

#4 2020-10-26-Mind-of-people-in-programming.md
  posts/2020-10-26-Mind-of-people-in-programming.md
Labels: hacktoberfest

#3 2020-10-26-Door-Censor-blog.md
  posts/2020-10-26-Door-Censor-blog.md
Labels: hacktoberfest

#5 Create 26-10-2020 COVID-19 and Technology.md
  posts/26-10-2020 COVID-19 and Technology.md
Labels: hacktoberfest

#7 Start Game Development with Unity
  2020-10-27-Start-Game-Development-with-Unity.md
Labels: hacktoberfest

#8 Create 2020-10-27-Emoji-Prediction-using-Hand-Gesture-Recognition.md
  2020-10-27-Emoji-Prediction-using-Hand-Gesture-Recognition.md
Labels: hacktoberfest

#9 Create 2020-10-27-virtual-reality.md
  2020-10-27-virtual-reality.md
Labels: hacktoberfest

#10 Create 28-10-2020 Augmented Reality.md
  posts/28-10-2020 Augmented Reality.md
Labels: hacktoberfest-accepted

#11 Create 2020-10-28-ArtificialNeurons.md
  posts/2020-10-28-ArtificialNeurons.md
Labels: hacktoberfest, hacktoberfest-accepted

#12 2020-10-28-Python-is-slow.md
  posts/2020-10-28-Python-is-slow.md
Labels: hacktoberfest-accepted

#13 Create 29.10.2020 Self driving car technology.md
  posts/29.10.2020 Self driving car technology.md
Labels: hacktoberfest

#14 2020-10-29-Solar-Charger.md
  2020-10-29-Secret-message-in-Java.md
  2020-10-29-Solar-Charger.md
Labels: hacktoberfest, hacktoberfest-accepted

#15 Create 2020-10-31-Start-with-java
  2020-10-31-Start-with-java
Labels: hacktoberfest, hacktoberfest-accepted

#16 Create 31.10.20 how netflix works.md
  posts/31.10.20 how netflix works.md
Labels: hacktoberfest
